export const sliderData =[
    {id:1,
    title:"Quality Male ",
    image:"/images/ads1.jpg",
    description: "DONT COMPROMISE ON STYLES!"},
{id:2,
    title:"Christmas Sales",
    image:"/images/ads2.jpg",
    description: "DONT COMPROMISE ON QUANLITY!"},
{id:3,
    title:"New Arrivals",
    image:"/images/ads3.jpg",
    description: "DONT COMPROMISE ON RELIABILITY!"},
{id:4,
        title:"Classy Female",
        image:"/images/female.jpg",
        description: "DONT COMPROMISE ON QUANLITY!"},
{id:5,
        title:"Just For Children",
        image:"/images/children.jpg",
        description: "DONT COMPROMISE ON RELIABILITY!"},
]